# Generated by Django 5.2.12 on 2026-04-06 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('owner_name', models.CharField(max_length=255, verbose_name='owner name')),
                ('name', models.CharField(choices=[('CURRENT', 'Current'), ('SAVINGS', 'Savings')], default='CURRENT', help_text='Type/Label of the account', max_length=20, verbose_name='name')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('EGP', 'Egyptian Pound')], default='USD', help_text='Currency code (e.g., USD, EUR)', max_length=3, verbose_name='currency')),
                ('balance', models.DecimalField(decimal_places=4, default=0, help_text='Current balance of the account (must be >= 0)', max_digits=20, verbose_name='balance')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'indexes': [models.Index(fields=['is_active'], name='idx_account_active'), models.Index(fields=['owner_name'], name='idx_account_owner'), models.Index(fields=['created_at'], name='idx_account_created')],
                'constraints': [models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='balance_not_negative')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10, verbose_name='type')),
                ('amount', models.DecimalField(decimal_places=4, help_text='Positive for Credit (+), Negative for Debit (-)', max_digits=20, verbose_name='amount')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('idempotency_key', models.CharField(blank=True, help_text='Unique key to prevent duplicate transaction processing', max_length=255, null=True, unique=True, verbose_name='idempotency key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ledger.account', verbose_name='account')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('destination_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfer', to='ledger.transaction', verbose_name='destination transaction')),
                ('source_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfer', to='ledger.transaction', verbose_name='source transaction')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-created_at'], name='idx_txn_created'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', '-created_at'], name='idx_txn_account_created'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'transaction_type', '-created_at'], name='idx_txn_account_type_created'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['-created_at'], name='idx_transfer_created'),
        ),
    ]
