# Generated by Django 5.2.12 on 2026-04-05 21:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('CURRENT', 'Current'), ('SAVINGS', 'Savings')], default='CURRENT', help_text='Type/Label of the account', max_length=20, verbose_name='name')),
                ('balance', models.DecimalField(decimal_places=4, default=0, help_text='Current balance of the account (must be >= 0)', max_digits=20, verbose_name='balance')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_accounts', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=4, help_text='Positive for Credit (+), Negative for Debit (-)', max_digits=20, verbose_name='amount')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('idempotency_key', models.UUIDField(blank=True, help_text='Unique key to prevent duplicate transaction processing', null=True, unique=True, verbose_name='idempotency key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ledger.account', verbose_name='account')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfer', to='ledger.transaction', verbose_name='destination transaction')),
                ('source_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfer', to='ledger.transaction', verbose_name='source transaction')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_active'], name='idx_account_active'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user', 'name'], name='idx_account_user_type'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['created_at'], name='idx_account_created'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='balance_not_negative'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-created_at'], name='idx_txn_created'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', '-created_at'], name='idx_txn_account_created'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['-created_at'], name='idx_transfer_created'),
        ),
    ]
