# Generated by Django 5.2.12 on 2026-04-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='account_type',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('CURRENT', 'Current'), ('SAVINGS', 'Savings')], default='CURRENT', help_text='Type/Label of the account', max_length=20, verbose_name='account type'),
        ),
    ]
