# Generated by Django 5.2.12 on 2026-04-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type_',
            field=models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], default='CREDIT', max_length=10, verbose_name='type_'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Unique key to prevent duplicate transaction processing', max_length=255, null=True, unique=True, verbose_name='idempotency key'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'type_', '-created_at'], name='idx_txn_account_type_created'),
        ),
    ]
