# Generated by Django 5.2.12 on 2026-04-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_remove_account_name_account_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='amount',
            field=models.DecimalField(decimal_places=4, help_text='Amount transferred (must be > 0)', max_digits=20, null=True, verbose_name='amount'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Unique key to prevent duplicate transfer processing', max_length=255, null=True, unique=True, verbose_name='idempotency key'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transfer_amount_positive'),
        ),
    ]
